/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
import type * as libs from "./libs";
export type { libs };
import type * as mock from "./mock";
export type { mock };
export type { ShootingCoinManager } from "./ShootingCoinManager";
export type { ShootingNFT } from "./ShootingNFT";
export type { ShootingRole } from "./ShootingRole";
export type { TestShootingCoin } from "./TestShootingCoin";
