/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IShootingNFT__factory } from "./IShootingNFT__factory";
export { IShootingRole__factory } from "./IShootingRole__factory";
