/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IShootingNFT,
  IShootingNFTInterface,
} from "../../../contracts/interface/IShootingNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "unStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IShootingNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IShootingNFTInterface {
    return new utils.Interface(_abi) as IShootingNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShootingNFT {
    return new Contract(address, _abi, signerOrProvider) as IShootingNFT;
  }
}
