/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IShootingGame,
  IShootingGameInterface,
} from "../../../contracts/interface/IShootingGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "userAccount",
        type: "address",
      },
    ],
    name: "checkOnGame",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IShootingGame__factory {
  static readonly abi = _abi;
  static createInterface(): IShootingGameInterface {
    return new utils.Interface(_abi) as IShootingGameInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShootingGame {
    return new Contract(address, _abi, signerOrProvider) as IShootingGame;
  }
}
