/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CurrencyController__factory } from "./CurrencyController__factory";
export { GameCore__factory } from "./GameCore__factory";
